apiVersion: v1
kind: Namespace
metadata:
  name: namespace-c

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-c
  namespace: namespace-c
  labels:
    app.kubernetes.io/name: service-c

---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: namespace-c
  labels:
    app.kubernetes.io/name: service-c
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 9080
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: service-c

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: namespace-c
  labels:
    app.kubernetes.io/name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-c
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-c
    spec:
      serviceAccountName: service-c
      containers:
        - name: service-c
          image: service_c:latest
          imagePullPolicy: Never
          ports:
            - name: grpc
              containerPort: 9080
              protocol: TCP
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9080"]
            initialDelaySeconds: 60
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9080"]
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 48Mi
