apiVersion: v1
kind: Namespace
metadata:
  name: namespace_a

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service_a
  namespace: namespace_a
  labels:
    app.kubernetes.io/name: service_a

---
apiVersion: v1
kind: Service
metadata:
  name: service_a
  namespace: namespace_a
  labels:
    app.kubernetes.io/name: service_a
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 9080
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: service_b

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_a
  namespace: namespace_a
  labels:
    app.kubernetes.io/name: service_a
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service_a
    spec:
      serviceAccountName: service_a
      containers:
        - name: service_a
          image: service_a:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 48Mi
