name: golangci-lint

on:
  workflow_call:
    inputs:
      GO_WORKING_DIR:
        required: true
        type: string
      GOLANGCI_LINT_VERSION:
        required: true
        type: string

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "${{ inputs.GO_WORKING_DIR }}/go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3.7.1
        with:
          version: "${{ inputs.GOLANGCI_LINT_VERSION }}"
          working-directory: "${{ inputs.GO_WORKING_DIR }}"
